name: Unzip Files

on:
  workflow_dispatch:  # This allows you to run the workflow manually

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unzip Files
        run: unzip your-zip-file.zip -d ./unzipped-files

      - name: Commit Unzipped Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          mv ./unzipped-files/* ./
          rm -rf ./unzipped-files your-zip-file.zip
          git add .
          git commit -m "Unzipped project files"
          git push
